### PR TITLE
JPEG-compressed GeoTIFF

### PR DESCRIPTION
**Pull request by mojodna**
Introduces a JPEG-compressed GeoTIFF to facilitate testing of naturalatlas/node-gdal#102 within mapnik-omnivore.

### CODE REVIEW

**Comment by springmeyer** [comment]
This file is 7 MB - could a smaller version be used and still be effective?

**Comment by mojodna** [comment]
Surely. How does 1.2K sound?  ;-)

**Comment by GretaCB** [comment]
:) 1.2K should be good

**Comment by mojodna** [comment]
Thanks!

**Comment by GretaCB** [comment]
:+1: Merged and published

**Pull request merged**
